Fix response body
dotsplatform/requests-logger pull request #6
Opened 2024-05-29 10:50 UTC by BoMa0103

2024-07-15 13:14 UTC, dotsplatform requested changes
Rename field in code, use response_data as text, just to prevent structure updates

2024-10-08 16:06 UTC, yehorherasymchuk approved these changes

2024-10-08 16:07 UTC, yehorherasymchuk approved these changes

2024-10-08 16:07 UTC, dotsplatform approved these changes

2024-10-08 16:08 UTC, merged